export type Language = 'EN' | 'DE' | 'FR';

export const translations = {
  EN: {
    nav: {
      whoWeAre: 'Who We Are',
      ourServices: 'Our Services',
      joinTeam: 'Join Our Team',
      getInTouch: 'Get In Touch',
    },
    hero: {
      title: 'Elegance Meets Excellence',
      subtitle: 'Premium hostess services for exclusive events across Middle Europe',
      forClients: 'For Clients',
      forHostesses: 'For Hostesses',
    },
    about: {
      title: 'Who We Are',
      paragraph1: "Roseélite is Middle Europe's premier hostess agency, connecting discerning clients with exceptional hospitality professionals.",
      paragraph2: 'We specialize in providing elegant, professional hostesses for corporate events, private gatherings, trade shows, and exclusive occasions across Austria, Germany, Switzerland, and neighboring regions.',
      paragraph3: 'Our commitment to excellence ensures every event is elevated with grace, sophistication, and impeccable service.',
    },
    services: {
      title: 'Our Services',
      subtitle: 'Tailored hospitality solutions for every occasion',
      corporate: {
        title: 'Corporate Events',
        description: 'Professional hostesses for conferences, product launches, and business galas',
      },
      private: {
        title: 'Private Functions',
        description: 'Elegant service for weddings, anniversaries, and exclusive private parties',
      },
      tradeShows: {
        title: 'Trade Shows',
        description: 'Experienced brand ambassadors and booth representatives',
      },
      vip: {
        title: 'VIP Services',
        description: 'Discreet, professional accompaniment for high-profile events',
      },
    },
    clients: {
      title: 'Just Some of Our Satisfied Clients',
      subtitle: 'Trusted by leading brands across Europe',
    },
    hostesses: {
      title: 'Join Our Team',
      subtitle: "Become part of Middle Europe's most respected hostess agency",
      benefitsTitle: 'Why Work With Roseélite?',
      benefits: [
        'Flexible scheduling around your commitments',
        'Competitive compensation and bonus opportunities',
        'Work at prestigious events and venues',
        'Professional development and training',
        'Safe, supportive work environment',
        'Networking with industry professionals',
      ],
      applyButton: 'Apply Now',
      applyNote: "We're always looking for professional, elegant, and reliable individuals",
    },
    contact: {
      title: 'Get In Touch',
      subtitle: 'Let us elevate your next event with exceptional hospitality',
      email: 'Email',
      phone: 'Phone',
      location: 'Location',
      locationValue: 'Vienna, Austria',
      form: {
        name: 'Name',
        email: 'Email',
        phone: 'Phone',
        message: 'Message',
        send: 'Send Message',
        success: 'Message Sent!',
        successDescription: "We'll get back to you as soon as possible.",
      },
      validation: {
        nameRequired: 'Name is required',
        emailInvalid: 'Invalid email address',
        phoneRequired: 'Phone is required',
        messageRequired: 'Message must be at least 10 characters',
      },
    },
    footer: {
      tagline: 'Premium Hostess Agency • Middle Europe',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      impressum: 'Impressum',
      copyright: 'All rights reserved.',
    },
  },
  DE: {
    nav: {
      whoWeAre: 'Über Uns',
      ourServices: 'Unsere Dienstleistungen',
      joinTeam: 'Werde Teil des Teams',
      getInTouch: 'Kontakt',
    },
    hero: {
      title: 'Eleganz trifft Exzellenz',
      subtitle: 'Premium Hostess-Services für exklusive Veranstaltungen in Mitteleuropa',
      forClients: 'Für Kunden',
      forHostesses: 'Für Hostessen',
    },
    about: {
      title: 'Über Uns',
      paragraph1: 'Roseélite ist Mitteleuropas führende Hostess-Agentur, die anspruchsvolle Kunden mit außergewöhnlichen Gastgeberprofis verbindet.',
      paragraph2: 'Wir sind spezialisiert auf die Bereitstellung eleganter, professioneller Hostessen für Firmenveranstaltungen, private Feiern, Messen und exklusive Anlässe in Österreich, Deutschland, der Schweiz und den Nachbarregionen.',
      paragraph3: 'Unser Engagement für Exzellenz stellt sicher, dass jede Veranstaltung mit Anmut, Raffinesse und tadellosem Service veredelt wird.',
    },
    services: {
      title: 'Unsere Dienstleistungen',
      subtitle: 'Maßgeschneiderte Hospitality-Lösungen für jeden Anlass',
      corporate: {
        title: 'Firmenveranstaltungen',
        description: 'Professionelle Hostessen für Konferenzen, Produkteinführungen und Business-Galas',
      },
      private: {
        title: 'Private Veranstaltungen',
        description: 'Eleganter Service für Hochzeiten, Jubiläen und exklusive private Partys',
      },
      tradeShows: {
        title: 'Messen',
        description: 'Erfahrene Markenbotschafter und Standbetreuer',
      },
      vip: {
        title: 'VIP-Services',
        description: 'Diskrete, professionelle Begleitung bei hochkarätigen Events',
      },
    },
    clients: {
      title: 'Einige unserer zufriedenen Kunden',
      subtitle: 'Vertrauen führender Marken in ganz Europa',
    },
    hostesses: {
      title: 'Werde Teil des Teams',
      subtitle: 'Werden Sie Teil von Mitteleuropas angesehenster Hostess-Agentur',
      benefitsTitle: 'Warum mit Roseélite arbeiten?',
      benefits: [
        'Flexible Zeitplanung für Ihre Verpflichtungen',
        'Wettbewerbsfähige Vergütung und Bonusmöglichkeiten',
        'Arbeit bei prestigeträchtigen Events und Veranstaltungsorten',
        'Professionelle Entwicklung und Schulung',
        'Sicheres, unterstützendes Arbeitsumfeld',
        'Networking mit Branchenprofis',
      ],
      applyButton: 'Jetzt bewerben',
      applyNote: 'Wir suchen immer professionelle, elegante und zuverlässige Persönlichkeiten',
    },
    contact: {
      title: 'Kontaktieren Sie uns',
      subtitle: 'Lassen Sie uns Ihre nächste Veranstaltung mit außergewöhnlicher Gastfreundschaft bereichern',
      email: 'E-Mail',
      phone: 'Telefon',
      location: 'Standort',
      locationValue: 'Wien, Österreich',
      form: {
        name: 'Name',
        email: 'E-Mail',
        phone: 'Telefon',
        message: 'Nachricht',
        send: 'Nachricht senden',
        success: 'Nachricht gesendet!',
        successDescription: 'Wir werden uns so schnell wie möglich bei Ihnen melden.',
      },
      validation: {
        nameRequired: 'Name ist erforderlich',
        emailInvalid: 'Ungültige E-Mail-Adresse',
        phoneRequired: 'Telefon ist erforderlich',
        messageRequired: 'Nachricht muss mindestens 10 Zeichen lang sein',
      },
    },
    footer: {
      tagline: 'Premium Hostess-Agentur • Mitteleuropa',
      privacy: 'Datenschutz',
      terms: 'Nutzungsbedingungen',
      impressum: 'Impressum',
      copyright: 'Alle Rechte vorbehalten.',
    },
  },
  FR: {
    nav: {
      whoWeAre: 'Qui Sommes-Nous',
      ourServices: 'Nos Services',
      joinTeam: 'Rejoignez Notre Équipe',
      getInTouch: 'Contactez-Nous',
    },
    hero: {
      title: "L'Élégance Rencontre l'Excellence",
      subtitle: "Services d'hôtesses premium pour événements exclusifs en Europe centrale",
      forClients: 'Pour les Clients',
      forHostesses: 'Pour les Hôtesses',
    },
    about: {
      title: 'Qui Sommes-Nous',
      paragraph1: "Roseélite est la première agence d'hôtesses d'Europe centrale, mettant en relation des clients exigeants avec des professionnels exceptionnels de l'hospitalité.",
      paragraph2: "Nous sommes spécialisés dans la fourniture d'hôtesses élégantes et professionnelles pour événements d'entreprise, réceptions privées, salons professionnels et occasions exclusives en Autriche, Allemagne, Suisse et régions voisines.",
      paragraph3: "Notre engagement envers l'excellence garantit que chaque événement soit sublimé avec grâce, sophistication et service impeccable.",
    },
    services: {
      title: 'Nos Services',
      subtitle: "Solutions d'hospitalité sur mesure pour chaque occasion",
      corporate: {
        title: "Événements d'Entreprise",
        description: 'Hôtesses professionnelles pour conférences, lancements de produits et galas d\'affaires',
      },
      private: {
        title: 'Fonctions Privées',
        description: 'Service élégant pour mariages, anniversaires et fêtes privées exclusives',
      },
      tradeShows: {
        title: 'Salons Professionnels',
        description: 'Ambassadrices de marque expérimentées et représentantes de stand',
      },
      vip: {
        title: 'Services VIP',
        description: 'Accompagnement discret et professionnel pour événements prestigieux',
      },
    },
    clients: {
      title: 'Quelques-uns de nos clients satisfaits',
      subtitle: 'La confiance des marques leaders en Europe',
    },
    hostesses: {
      title: 'Rejoignez Notre Équipe',
      subtitle: "Faites partie de l'agence d'hôtesses la plus respectée d'Europe centrale",
      benefitsTitle: 'Pourquoi travailler avec Roseélite?',
      benefits: [
        'Horaires flexibles selon vos engagements',
        'Rémunération compétitive et opportunités de bonus',
        "Travail lors d'événements et lieux prestigieux",
        'Développement professionnel et formation',
        'Environnement de travail sûr et favorable',
        'Réseautage avec des professionnels du secteur',
      ],
      applyButton: 'Postuler Maintenant',
      applyNote: 'Nous recherchons toujours des personnes professionnelles, élégantes et fiables',
    },
    contact: {
      title: 'Contactez-Nous',
      subtitle: 'Laissez-nous élever votre prochain événement avec une hospitalité exceptionnelle',
      email: 'Email',
      phone: 'Téléphone',
      location: 'Localisation',
      locationValue: 'Vienne, Autriche',
      form: {
        name: 'Nom',
        email: 'Email',
        phone: 'Téléphone',
        message: 'Message',
        send: 'Envoyer le Message',
        success: 'Message Envoyé!',
        successDescription: 'Nous vous répondrons dans les plus brefs délais.',
      },
      validation: {
        nameRequired: 'Le nom est requis',
        emailInvalid: 'Adresse email invalide',
        phoneRequired: 'Le téléphone est requis',
        messageRequired: 'Le message doit contenir au moins 10 caractères',
      },
    },
    footer: {
      tagline: "Agence d'Hôtesses Premium • Europe Centrale",
      privacy: 'Politique de Confidentialité',
      terms: "Conditions d'Utilisation",
      impressum: 'Mentions Légales',
      copyright: 'Tous droits réservés.',
    },
  },
};
